name: 'Scripts Check'

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches: [master]
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  flake8:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Set up Poetry cache for Python dependencies
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          curl -fsS -o install-poetry.py https://install.python-poetry.org/
          python install-poetry.py --version 1.3.2
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version
      - name: Get repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --upgrade setuptools
          poetry install --no-interaction --no-root --with=dev
      - name: Run flask8 checks
        run: poetry run python -m flake8
